name: vr_hack
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.4.2
  webview_flutter_android: ^3.15.0
  webview_flutter_wkwebview: ^3.10.0
  intl: ^0.18.1  # For time formatting
  timer_builder: ^2.0.0  # For timed updates
  shared_preferences: ^2.2.2
  shared_preferences_android: ^2.2.1
  animated_text_kit: ^4.2.2
  html: ^0.15.5
  google_fonts: ^6.1.0
  firebase_core: ^2.24.2
  firebase_remote_config: ^4.3.10
  url_launcher: ^6.2.4
  cloud_firestore: ^4.17.5
  firebase_auth: ^4.16.0
  http: ^1.1.2
  path_provider: ^2.1.1
  lottie: ^3.3.1
  audioplayers: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - C:/Users/vr812/Desktop/Projects/vr_hack/register voice.ogg

fonts:
  - family: ChakraPetch
    fonts:
      - asset: fonts/ChakraPetch-Regular.ttf
      - asset: fonts/ChakraPetch-Bold.ttf
  - family: RobotoMono
    fonts:
      - asset: fonts/RobotoMono-Regular.ttf
      - asset: fonts/RobotoMono-Bold.ttf
  - family: Orbitron
    fonts:
      - asset: fonts/Orbitron-Regular.ttf
      - asset: fonts/Orbitron-Medium.ttf
      - asset: fonts/Orbitron-Bold.ttf
