// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLmbJhRUELvq4eSKce8y9dLUvaDpMrzVs',
    appId: '1:1077905243440:web:b02e211e325e8f66999cf5',
    messagingSenderId: '1077905243440',
    projectId: 'vasu-hacks',
    authDomain: 'vasu-hacks.firebaseapp.com',
    storageBucket: 'vasu-hacks.firebasestorage.app',
    measurementId: 'G-B75QWWH4DM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBryRAra7wKM8oww0gMZWgTFoS9RxS5poI',
    appId: '1:1077905243440:android:dfb5d86ecb946a89999cf5',
    messagingSenderId: '1077905243440',
    projectId: 'vasu-hacks',
    storageBucket: 'vasu-hacks.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDygcs4zMn-IgbQ83v46WWa_xbEY86HkmQ',
    appId: '1:1077905243440:ios:b7de9bda87e413ef999cf5',
    messagingSenderId: '1077905243440',
    projectId: 'vasu-hacks',
    storageBucket: 'vasu-hacks.firebasestorage.app',
    iosBundleId: 'com.example.vrHack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDygcs4zMn-IgbQ83v46WWa_xbEY86HkmQ',
    appId: '1:1077905243440:ios:b7de9bda87e413ef999cf5',
    messagingSenderId: '1077905243440',
    projectId: 'vasu-hacks',
    storageBucket: 'vasu-hacks.firebasestorage.app',
    iosBundleId: 'com.example.vrHack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLmbJhRUELvq4eSKce8y9dLUvaDpMrzVs',
    appId: '1:1077905243440:web:42b2ee912dc09b83999cf5',
    messagingSenderId: '1077905243440',
    projectId: 'vasu-hacks',
    authDomain: 'vasu-hacks.firebaseapp.com',
    storageBucket: 'vasu-hacks.firebasestorage.app',
    measurementId: 'G-E91H41338Z',
  );

}